site_name: AVR-IOE
repo_url: https://github.com/Cynerd/avr-ioe.git
site_description: AVR microcontroller input/output expansion code
copyright: GNU General Public License, version 2.0
pages:
- Home: index.md
- Usage: usage.md
- References:
    - IO Ports: references/ioport.md
    - SPI: references/spi.md
    - Tasks: references/tasks.md
    - Jobs: references/jobs.md
    - Timer: references/timer.md
    - USART: references/usart.md
    - Utils:
        - Buffer: references/utils/buffer.md
        - NArray: references/utils/narray.md
- Adding MCU support: add_support.md
- Miscellanoues:
    - Jobs vs. Tasks: miscelaneous/jobs_vs_tasks.md
theme: readthedocs

site_dir: html
