site_name: AVR-IOE
repo_url: https://github.com/Cynerd/avr-ioe.git
site_description: AVR microcontroller input/output expansion code
copyright: GNU General Public License, version 2.0
pages:
- Home: index.md
- Usage: usage.md
- Parts:
    - IO Ports: parts/ioport.md
    - SPI: parts/spi.md
    - Tasks: parts/tasks.md
    - Jobs: parts/jobs.md
    - Timer: parts/timer.md
    - USART: parts/usart.md
    - Utils:
        - Buffer: parts/utils/buffer.md
        - NArray: parts/utils/narray.md
- Adding MCU support: add_support.md
- Miscellanoues:
    - Jobs vs. Tasks: miscellanoues/jobs_vs_tasks.md
theme: readthedocs

site_dir: html
